### ISSUE TITLE
A veces peta la app cuando logueas

### ISSUE THREAD

**Issue by John-Development** [marinagot/MyFirstAidKitJ#8]
En la línea
Navigation.findNavController(v).navigate(R.id.action_login_to_home);
del login salta una excepcion con el siguiente mensaje

java.lang.IllegalStateException: View android.support.v7.widget.AppCompatButton{a38309a VFED..C.. ...P.... 207,1407-459,1533 #7f09003b app:id/btn_sign_in} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:83)
        at com.example.myfirstaidkit.login$2.onClick(login.java:104)

**Comment by John-Development** [comment]
He comentado la línea hasta que se solucione (en master)

**Comment by John-Development** [comment]
Corregido y terminado
